<div style="float:right; padding-top: 15px; padding-right: 15px">
    <div>
        <a href="https://whiteboxml.com">
            <img src="https://whiteboxml.com/static/img/logo/black_bg_white.svg" width="250">
        </a>
    </div>
</div>

# Numpy

In [1]:
import numpy as np

The basic data structures in Numpy are arrays, which can be used to represent tabular data. You can think of arrays as lists of lists.
The size of an array is the total number of elements in every list. The shape of an array is the size of the array along each dimension

In [2]:
np.zeros((2))

array([0., 0.])

In [3]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
a = np.zeros((3,4,2))

a

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [5]:
print(len(a))
print(a.size)
print(a.shape)

3
24
(3, 4, 2)


In [6]:
np.zeros((3,4,2,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [7]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
a = np.random.random((10,4))

a

array([[0.50018252, 0.2080104 , 0.41620774, 0.1799767 ],
       [0.82754532, 0.96810211, 0.24119849, 0.68105781],
       [0.07732111, 0.33856294, 0.50245453, 0.54166655],
       [0.03471378, 0.49031715, 0.47344237, 0.20761334],
       [0.74700482, 0.09587075, 0.82230558, 0.22810159],
       [0.39023308, 0.13351523, 0.79053718, 0.77084971],
       [0.37818928, 0.18861634, 0.18828209, 0.63396135],
       [0.41259628, 0.45948957, 0.20642313, 0.88920033],
       [0.72195241, 0.53874726, 0.49911502, 0.70992297],
       [0.35806084, 0.26309429, 0.08504982, 0.38920374]])

In [9]:
my_array_random = [np.random.choice(x) for x in a]

np.random.choice(my_array_random)

0.1335152317732703

In [10]:
np.random.choice(a[0])

0.4162077375255533

In [11]:
np.reshape(a, a.size)

array([0.50018252, 0.2080104 , 0.41620774, 0.1799767 , 0.82754532,
       0.96810211, 0.24119849, 0.68105781, 0.07732111, 0.33856294,
       0.50245453, 0.54166655, 0.03471378, 0.49031715, 0.47344237,
       0.20761334, 0.74700482, 0.09587075, 0.82230558, 0.22810159,
       0.39023308, 0.13351523, 0.79053718, 0.77084971, 0.37818928,
       0.18861634, 0.18828209, 0.63396135, 0.41259628, 0.45948957,
       0.20642313, 0.88920033, 0.72195241, 0.53874726, 0.49911502,
       0.70992297, 0.35806084, 0.26309429, 0.08504982, 0.38920374])

In [12]:
np.reshape(a, (a.size, 1, 1)).shape

(40, 1, 1)

In [13]:
print(a.shape)
print(a.size)

(10, 4)
40


In [14]:
# first row
a[0]

array([0.50018252, 0.2080104 , 0.41620774, 0.1799767 ])

In [15]:
# first column
a[:,0]

array([0.50018252, 0.82754532, 0.07732111, 0.03471378, 0.74700482,
       0.39023308, 0.37818928, 0.41259628, 0.72195241, 0.35806084])

In [16]:
a[4,2]

0.8223055821147047

In [17]:
a[4][2]

0.8223055821147047

In [18]:
lst_lst = [[1,2,3],[4,5,6],[7,8,9]]
d = np.array(lst_lst)
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
d.shape

(3, 3)

In [20]:
lst_lst = [[1,2,3],[4,5,6],[7,8,9,10]]
unbalanced = np.array(lst_lst)
unbalanced

array([list([1, 2, 3]), list([4, 5, 6]), list([7, 8, 9, 10])],
      dtype=object)

In [21]:
unbalanced.shape

(3,)

In [22]:
np.sum(d)

45

In [23]:
np.sum(d[:,0])

12

In [24]:
np.sum(d[1,:])

15

In [25]:
np.sum(d[1])

15

In [26]:
np.sum(d, axis=0)

array([12, 15, 18])

In [27]:
np.sum(d, axis=1)

array([ 6, 15, 24])

In [28]:
np.mean(d)

5.0

In [29]:
np.mean(d, axis=0)

array([4., 5., 6.])

In [30]:
np.mean(d, axis=1)

array([2., 5., 8.])

## Operator overload

In [31]:
x = np.array([[1,2], [1,0]])
x

array([[1, 2],
       [1, 0]])

In [32]:
y = np.array([[1,2], [1,1]])
y

array([[1, 2],
       [1, 1]])

In [33]:
x + y

array([[2, 4],
       [2, 1]])

In [34]:
np.add(x,y)

array([[2, 4],
       [2, 1]])

In [35]:
np.concatenate([x, y])

array([[1, 2],
       [1, 0],
       [1, 2],
       [1, 1]])

In [36]:
?np.concatenate

Docstring:
concatenate((a1, a2, ...), axis=0, out=None)

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.

Returns
-------
res : ndarray
    The concatenated array.

See Also
--------
ma.concatenate : Concatenate function that preserves input masks.
array_split : Split an array into multiple sub-arrays of equal or
              near-equal size.
split : Split array into a list of multiple sub-arrays of equal size.
hsplit : Split array into multiple sub-arrays horizontally 

In [37]:
x - y

array([[ 0,  0],
       [ 0, -1]])

In [38]:
np.subtract(x,y)

array([[ 0,  0],
       [ 0, -1]])

In [39]:
x * y

array([[1, 4],
       [1, 0]])

In [40]:
np.multiply(x,y)

array([[1, 4],
       [1, 0]])

In [41]:
x / y

array([[1., 1.],
       [1., 0.]])

In [42]:
np.divide(x,y)

array([[1., 1.],
       [1., 0.]])

In [43]:
np.matmul(x,y)

array([[3, 4],
       [1, 2]])

In [44]:
x

array([[1, 2],
       [1, 0]])

In [45]:
y

array([[1, 2],
       [1, 1]])

<div style="padding-top: 25px; float: right">
    <div>    
        <i>&nbsp;&nbsp;© Copyright by</i>
    </div>
    <div>
        <a href="https://whiteboxml.com">
            <img src="https://whiteboxml.com/static/img/logo/black_bg_white.svg" width="125">
        </a>
    </div>
</div>